spring:
  datasource:
    url: jdbc:mysql://tuxa.sme.utc/sr03p026
    username: sr03p026
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    show-sql: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true